#!/bin/bash

#################################
#
#  Usage: ./e2eTest test/end_to_end/raw_results
#
#################################

MINUTE=60
HOUR=3600

experiment_path=$1

python="$HOME/.virtualenvs/pyanimats/bin/python" # ToDo: should this be `which python` instead, so it gets the current env's python?

seed_start=0
num_cores=1


# This is specific to the End to End test
init_genome_path="test/end_to_end/init_genome"

echo "PyAnimats multi-seed simulation ($(date))"
echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "Rebuilding animat C++ extension..."
rm -r build && rm animat.cpython-34m.so && $python setup.py build_ext --inplace &> /dev/null && echo "...finished."
echo ""


# compile the HMU constants file
$python animats/helpers/compile_constants.py $experiment_path  #raw_results/hmu_test/


datename="$(date +%s)" # - $(date)" # name each run the time it was ran as <seconds> - <human readable>
output_dir=$experiment_path # "test/end_to_end/raw_results" 
echo "Writing results to '$output_dir'."
echo ""

for ((seed=$seed_start; seed < $(($seed_start + $num_cores)); seed++))
do
  # Get the output with the seed directory included.
  cur_output_dir="$output_dir/$datename/seed-$seed"
  mkdir "$output_dir/$datename"
  mkdir "$cur_output_dir"
  cp "$output_dir/experiment.yml" "$cur_output_dir/experiment.yml"
  # Build the command.
  cmd="$python ./pyanimats.py $cur_output_dir" # --seed=123
  # Append the intial genome option if it is set.
  [[ ! -z $init_genome_path ]] && cmd="$cmd -g $init_genome_path"
  # Display command.
  echo "Executing command:"
  echo $cmd
  echo ""
  # Ensure the output directory exists.
  mkdir -p $cur_output_dir
  # Run it!
  unbuffer $cmd 2>&1 | tee "$cur_output_dir/output.log" && echo "[Seed $seed] Wrote results to '$cur_output_dir'." &
  
done
# cd test/end_to_end
# nosetests e2etest.py
# cd ../..
